name:                countdown-perf
version:             0.1.0.0
github:              "Vincibean/countdown-perf"
license:             GPL-3.0
author:              "Vincibean"
maintainer:          "andrebessi00@gmail.com"
copyright:           "2020 Vincibean"

extra-source-files:
- README.md

description:         Please see the README on GitHub at <https://github.com/githubuser/countdown-perf#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  countdown-perf-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - countdown-perf

tests:
  countdown-perf-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - countdown-perf
    - hspec
    - QuickCheck
